//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BengaliFoodOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodmenuItem
    {
        public int FoodItemID { get; set; }
        public string FoodItemName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> MainCourse { get; set; }
        public string Active { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
