//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BengaliFoodOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderdetailID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> FoodItemID { get; set; }
        public Nullable<int> ItemPrice { get; set; }
        public Nullable<int> ItemExtra { get; set; }
        public Nullable<int> ItemDelivery { get; set; }
        public Nullable<int> ItemTotal { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> ItemQuantity { get; set; }
    }
}
