//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BengaliFoodOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItem
    {
        public int CartID { get; set; }
        public Nullable<int> CartorderID { get; set; }
        public Nullable<System.DateTime> CartDate { get; set; }
        public string CartUniqID { get; set; }
        public Nullable<int> CartCustomerID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<int> CartAmount { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
